// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button.vue')['default']
    Card: typeof import('./src/components/welcome/components/card.vue')['default']
    First: typeof import('./src/components/welcome/first.vue')['default']
    FloatButton: typeof import('./src/components/floatButton.vue')['default']
    Fourth: typeof import('./src/components/welcome/fourth.vue')['default']
    InputPad: typeof import('./src/components/inputPad.vue')['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    Overlay: typeof import('./src/components/overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Second: typeof import('./src/components/welcome/second.vue')['default']
    Tab: typeof import('./src/components/tab.vue')['default']
    Tabs: typeof import('./src/components/tabs.vue')['default']
    Third: typeof import('./src/components/welcome/third.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
